
const plans = [
  {
    PID: "1",
    Name: "Push",
    EIDs: [1, 3, 40, 8, 69],
    Type: "Plan",
    Description: "A basic plan to improve your chest, triceps, and shoulder strength.",
    Difficulty: "Intermediate",
    Duration: 90,
    CDate: new Date(),
    LUDate: new Date(),
    Keywords: "Push workout, chest, shoulders, strength, triceps, bench press, incline press, machine press, dumbbell, gains",
    Public: false,
    Saved: false,
    CanBeCombinedWith: ["2", "3"]
  },
  {
    PID: "2",
    Name: "Pull",
    EIDs: [14, 15, 31, 32, 67],
    Type: "Plan",
    Description: "Focuses on building strength in the back and biceps for a balanced physique.",
    Difficulty: "Intermediate",
    Duration: 90,
    CDate: new Date(),
    LUDate: new Date(),
    Keywords: "Pull workout, back, biceps, rows, lats, strength, barbell row, pull-up, cable row, hypertrophy",
    Public: true,
    Saved: false,
    CanBeCombinedWith: ["1", "3"]
  },
  {
    PID: "3",
    Name: "Leg Day",
    EIDs: [19, 20, 21, 22, 25],
    Type: "Plan",
    Description: "A comprehensive leg workout designed to target quads, hamstrings, and glutes.",
    Difficulty: "Advanced",
    Duration: 90,
    CDate: new Date(),
    LUDate: new Date(),
    Keywords: "Leg day, quads, hamstrings, glutes, squats, leg press, lunges, strength, hypertrophy, definition",
    Public: false,
    Saved: false,
    CanBeCombinedWith: ["1", "2"]
  },
  {
    PID: "4",
    Name: "Upper Body",
    EIDs: [1, 3, 8, 14, 32],
    Type: "Plan",
    Description: "Targets chest, back, and shoulder muscles for balanced upper body strength.",
    Difficulty: "Intermediate",
    Duration: 75,
    CDate: new Date(),
    LUDate: new Date(),
    Keywords: "Upper body, chest, back, shoulders, strength, hypertrophy, bench press, rows, triceps",
    Public: true,
    Saved: false,
    CanBeCombinedWith: ["5", "6"]
  },
  {
    PID: "5",
    Name: "Lower Body",
    EIDs: [19, 20, 23, 28, 25],
    Type: "Plan",
    Description: "A lower body workout that focuses on quads, hamstrings, and glutes.",
    Difficulty: "Intermediate",
    Duration: 75,
    CDate: new Date(),
    LUDate: new Date(),
    Keywords: "Lower body, quads, glutes, hamstrings, strength, lunges, squats, hypertrophy, deadlift, definition",
    Public: false,
    Saved: false,
    CanBeCombinedWith: ["4", "6"]
  },
  {
    PID: "6",
    Name: "Full Body",
    EIDs: [1, 14, 19, 3, 69],
    Type: "Plan",
    Description: "A full body workout for those looking to improve overall strength and endurance.",
    Difficulty: "Beginner",
    Duration: 60,
    CDate: new Date(),
    LUDate: new Date(),
    Keywords: "Full body, chest, back, legs, endurance, strength, balanced workout, hypertrophy, beginner-friendly",
    Public: true,
    Saved: false,
    CanBeCombinedWith: ["7", "8"]
  },
  {
    PID: "7",
    Name: "Core Focus",
    EIDs: [44, 45, 47, 48, 49],
    Type: "Plan",
    Description: "Designed to strengthen and define the core and abdominal muscles.",
    Difficulty: "Intermediate",
    Duration: 45,
    CDate: new Date(),
    LUDate: new Date(),
    Keywords: "Core, abs, obliques, stability, endurance, definition, crunches, planks, intermediate",
    Public: true,
    Saved: false,
    CanBeCombinedWith: ["1", "5"]
  },
  {
    PID: "8",
    Name: "Glute & Hamstring",
    EIDs: [23, 28, 25, 68, 52],
    Type: "Plan",
    Description: "Focused on building and strengthening glutes and hamstrings.",
    Difficulty: "Intermediate",
    Duration: 60,
    CDate: new Date(),
    LUDate: new Date(),
    Keywords: "Glutes, hamstrings, lower body, strength, hypertrophy, lunges, deadlift, leg curl, machine exercises",
    Public: false,
    Saved: false,
    CanBeCombinedWith: ["5", "6"]
  },
  {
    PID: "9",
    Name: "Shoulders & Triceps",
    EIDs: [8, 69, 40, 38, 55],
    Type: "Plan",
    Description: "Targets shoulder and tricep muscles for upper body strength and definition.",
    Difficulty: "Advanced",
    Duration: 60,
    CDate: new Date(),
    LUDate: new Date(),
    Keywords: "Shoulders, triceps, upper body, hypertrophy, strength, dumbbells, cable, shoulder press, lateral raise",
    Public: true,
    Saved: false,
    CanBeCombinedWith: ["4", "10"]
  },
  {
    PID: "10",
    Name: "Chest & Biceps",
    EIDs: [1, 3, 34, 35, 36],
    Type: "Plan",
    Description: "A workout focused on building strength and mass in the chest and biceps.",
    Difficulty: "Intermediate",
    Duration: 75,
    CDate: new Date(),
    LUDate: new Date(),
    Keywords: "Chest, biceps, upper body, hypertrophy, strength, barbell, dumbbell curls, bench press, definition",
    Public: false,
    Saved: false,
    CanBeCombinedWith: ["9", "7"]
  },
  {
    PID: "11",
    Name: "Powerlifting Basics",
    EIDs: [1, 19, 11, 14, 65],
    Type: "Plan",
    Description: "Introductory powerlifting program focusing on the three major lifts: squat, bench press, and deadlift.",
    Difficulty: "Advanced",
    Duration: 90,
    CDate: new Date(),
    LUDate: new Date(),
    Keywords: "Powerlifting, squat, bench, deadlift, strength, barbell, heavy lifting, hypertrophy",
    Public: false,
    Saved: false,
    CanBeCombinedWith: ["12"]
  },
  {
    PID: "12",
    Name: "Strength & Conditioning",
    EIDs: [15, 20, 23, 32, 68],
    Type: "Plan",
    Description: "A balance of strength training and conditioning for overall athletic development.",
    Difficulty: "Intermediate",
    Duration: 75,
    CDate: new Date(),
    LUDate: new Date(),
    Keywords: "Strength, conditioning, balance, endurance, hypertrophy, kettlebell, dumbbell, full body",
    Public: true,
    Saved: false,
    CanBeCombinedWith: ["11"]
  },
  {
    PID: "13",
    Name: "Hypertrophy Specialization",
    EIDs: [1, 3, 14, 20, 28],
    Type: "Plan",
    Description: "Focused on hypertrophy to maximize muscle growth across the entire body.",
    Difficulty: "Intermediate",
    Duration: 90,
    CDate: new Date(),
    LUDate: new Date(),
    Keywords: "Hypertrophy, muscle growth, full body, strength, dumbbells, machines, isolation exercises",
    Public: false,
    Saved: false,
    CanBeCombinedWith: ["14"]
  },
  {
    PID: "14",
    Name: "Lean & Tone",
    EIDs: [10, 23, 44, 69, 47],
    Type: "Plan",
    Description: "A workout plan designed to burn fat and tone muscles with a blend of cardio and resistance exercises.",
    Difficulty: "Beginner",
    Duration: 60,
    CDate: new Date(),
    LUDate: new Date(),
    Keywords: "Toning, lean muscle, endurance, cardio, light weights, fat burn, high reps",
    Public: true,
    Saved: false,
    CanBeCombinedWith: ["13"]
  },
  {
    PID: "15",
    Name: "Explosive Power",
    EIDs: [27, 14, 21, 68, 32],
    Type: "Plan",
    Description: "Focuses on building explosive strength and power with plyometrics and strength movements.",
    Difficulty: "Advanced",
    Duration: 75,
    CDate: new Date(),
    LUDate: new Date(),
    Keywords: "Explosive power, plyometrics, strength, kettlebell swings, jump squats, athletic performance",
    Public: false,
    Saved: false,
    CanBeCombinedWith: ["16"]
  },
  {
    PID: "16",
    Name: "Upper/Lower Split",
    EIDs: [1, 14, 19, 21, 3],
    Type: "Plan",
    Description: "A classic upper/lower body split to maximize recovery and strength gains.",
    Difficulty: "Intermediate",
    Duration: 75,
    CDate: new Date(),
    LUDate: new Date(),
    Keywords: "Upper body, lower body, split workout, strength, recovery, compound movements",
    Public: false,
    Saved: false,
    CanBeCombinedWith: ["15"]
  },
  {
    PID: "17",
    Name: "Bodyweight Basics",
    EIDs: [45, 44, 48, 39, 76],
    Type: "Plan",
    Description: "A no-equipment workout plan focusing on building strength and endurance with bodyweight exercises.",
    Difficulty: "Beginner",
    Duration: 45,
    CDate: new Date(),
    LUDate: new Date(),
    Keywords: "Bodyweight, no equipment, core, endurance, full body, at home workout, push-ups, squats",
    Public: true,
    Saved: false,
    CanBeCombinedWith: ["18"]
  },
  {
    PID: "18",
    Name: "High Intensity Interval Training (HIIT)",
    EIDs: [47, 10, 31, 45, 68],
    Type: "Plan",
    Description: "Intense intervals of cardio and strength exercises for fat loss and endurance.",
    Difficulty: "Intermediate",
    Duration: 30,
    CDate: new Date(),
    LUDate: new Date(),
    Keywords: "HIIT, cardio, endurance, fat burn, high intensity, interval training, core, full body",
    Public: true,
    Saved: false,
    CanBeCombinedWith: ["17"]
  },
  {
    PID: "19",
    Name: "CrossFit Inspired",
    EIDs: [1, 14, 23, 68, 39],
    Type: "Plan",
    Description: "A functional fitness workout inspired by CrossFit, combining strength, cardio, and high-intensity intervals.",
    Difficulty: "Advanced",
    Duration: 60,
    CDate: new Date(),
    LUDate: new Date(),
    Keywords: "CrossFit, functional fitness, cardio, strength, high intensity, Olympic lifts, athletic",
    Public: false,
    Saved: false,
    CanBeCombinedWith: ["20"]
  },
  {
    PID: "20",
    Name: "Mobility & Flexibility",
    EIDs: [44, 46, 48, 62, 7],
    Type: "Plan",
    Description: "Focused on improving flexibility and mobility for injury prevention and recovery.",
    Difficulty: "Beginner",
    Duration: 30,
    CDate: new Date(),
    LUDate: new Date(),
    Keywords: "Mobility, flexibility, injury prevention, stretching, core stability, recovery, range of motion",
    Public: true,
    Saved: false,
    CanBeCombinedWith: ["19"]
  }

];

export default plans;
